version: '3.7'
x-network_mode: &default-network-mode bridge
x-restart: &default-restart always
x-logging: &default-logging
  options:
    max-size: '200k'
    max-file: '1'
  driver: json-file
x-volume: &default-volume
  - './data:/bitnami/redis/data'

services:
  redis:
    container_name: cc_redis
    image: bitnami/redis:latest
    env_file: ./redis.env
    ports:
      - '127.0.0.1:6379:6379'
    volumes: *default-volume
    network_mode: *default-network-mode
    restart: *default-restart
    logging: *default-logging
    depends_on:
      - permission

  permission:
    image: busybox:latest
    container_name: cc_redis_permission
    environment:
      - DATA_PATH=/bitnami/redis/data
      - NOTICE=/tmp/notice.txt
    user: root
    command: sh -c 'chmod 777 $${DATA_PATH} && env > $${NOTICE} && tail -f $${NOTICE}'
    network_mode: *default-network-mode
    volumes: *default-volume
    restart: *default-restart
    logging: *default-logging
