export const Millisecond = 1000;

export enum Second {
  ONE_SECOND = 1,
  TEN_SECOND = 10,
  THIRTY_SECONDS = 30,
  ONE_MINUTES = 60,
  FIVE_MINUTES = 5 * ONE_MINUTES,
  FIFTEEN_MINUTES = 15 * ONE_MINUTES,
  THIRTY_MINUTES = 30 * ONE_MINUTES,
  SIXTY_MINUTES = 60 * ONE_MINUTES,
}

export enum Minutes {
  ONE_MINITES = 1,
  FIVE_MINUTES = 5,
  FIFTEEN_MINUTES = 15,
  THIRTY_MINUTES = 30,
  SIXTY_MINUTES = 60,
}
